---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: ls4-liuserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-shell
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 95089,96414,103988
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-shell
    spec:
      affinity: {}
      containers:
      - name: shell
        image: registry.nersc.gov/m4616/raknop/liuserver-shell
        env:
        - name: PGHOST
          value: postgres
        - name: PGUSER
          value: ls_xgboost
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pgpass
        - name: PGNAME
          value: ls_xgboost
        imagePullPolicy: Always
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
          - mountPath: /secrets
            name: secrets
          - mountPath: /code
            name: code
          - mountPath: /pqdata
            name: pqdata
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 103988
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
        - name: secrets
          secret:
            defaultMode: 292
            optional: false
            secretName: secrets
        - hostPath:
            path: /global/cfs/cdirs/m4616/users/raknop/liu-ls-server
            type: Directory
          name: code
        - hostPath:
            path: /global/cfs/cdirs/m4616/users/cliu
            type: Directory
          name: pqdata
---
apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: ls4-liuserver
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-shell
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
