---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: ls4-liuserver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-webserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 95089,96414,103988
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-webserver
    spec:
      affinity: {}
      containers:
      - name: webserver
        image: registry.nersc.gov/m4616/raknop/liuserver
        env:
        - name: PGHOST
          value: postgres
        - name: PGUSER
          value: ls_xgboost
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: pgpass
        - name: PGNAME
          value: ls_xgboost
        imagePullPolicy: Always
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: ls4-liuserver
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-ingress
  namespace: ls4-liuserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-ls4-liuserver-webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nersc.gov/clustername: production
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: 500m
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  name: webserver
  namespace: ls4-liuserver
spec:
  rules:
  - host: webserver.ls4-liuserver.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: webserver-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: ls-xgboost.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: webserver-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ls4-liuserver.lbl.gov
    secretName: webserver-cert
---
